### ISSUE TITLE
Maven repo unavailable

### ISSUE THREAD

**Issue by hsanson** [47deg/android-swipelistview#215]
All of the sudden my build stopped working becuase the maven repo: http://clinker.47deg.com/nexus/content/groups/public is not available anymore.

I get this error after 8 minutes wait:

```
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not resolve com.fortysevendeg.swipelistview:swipelistview:1.0-SNAPSHOT.
     Required by:
         :myproject:unspecified
      > Unable to load Maven meta-data from http://clinker.47deg.com/nexus/content/groups/public/com/fortysevendeg/swipelistview/swipelistview/1.0-SNAPSHOT/maven-metadata
.xml.
         > Could not GET 'http://clinker.47deg.com/nexus/content/groups/public/com/fortysevendeg/swipelistview/swipelistview/1.0-SNAPSHOT/maven-metadata.xml'.
            > Connection to http://clinker.47deg.com refused

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8 mins 48.043 secs

```

**Comment by YarikSOffice** [comment]
Have got the same error..

**Comment by pablonajt** [comment]
refs #225

**Comment by hsanson** [comment]
Seems to working again now. The problem was related to ISP provider blocking some IP addresses....

**Comment by oguzozcan** [comment]
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not resolve com.fortysevendeg.swipelistview:swipelistview:1.0-SNAPSHOT.
     Required by:
         FashionTalks:app:unspecified
      > Unable to load Maven meta-data from http://clinker.47deg.com/nexus/content/groups/public/com/fortysevendeg/swipelistview/swipelistview/1.0-SNAPSHOT/maven-metadata.xml.
         > Could not GET 'http://clinker.47deg.com/nexus/content/groups/public/com/fortysevendeg/swipelistview/swipelistview/1.0-SNAPSHOT/maven-metadata.xml'.
            > Connection to http://clinker.47deg.com refused
