### ISSUE TITLE
No such property: mavenDeployer for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

### ISSUE THREAD

**Issue by spartawhy117** [47deg/android-swipelistview#226]
No such property: mavenDeployer for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer
use intellij idea 14.0.3，log cat like this :
2015-03-07 04:25:03,935 [ 904534]   WARN - nal.AbstractExternalSystemTask - No such property: mavenDeployer for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer 
com.intellij.openapi.externalSystem.model.LocationAwareExternalSystemException: No such property: mavenDeployer for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

**Comment by mafergus** [comment]
I'm having the same issues - what was your fix??

**Comment by lxz612** [comment]
I can't open it too.
